/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityEntryType } from './activityEntryType';


export interface ActivityEntryDto { 
    type: ActivityEntryType;
    id: string;
    createdAt: string;
    createdBy: string;
    note?: string | null;
    amountCents: number;
    runningBalanceCents: number;
    count?: number | null;
    delta?: number | null;
    weightGrams?: number | null;
    privateAmountCents?: number | null;
    kittyAmountCents?: number | null;
    beanName?: string | null;
    ratingValue?: number | null;
}
export namespace ActivityEntryDto {
}


