/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ActivityEntryType = {
    Consumption: 'CONSUMPTION',
    ConsumptionCancel: 'CONSUMPTION_CANCEL',
    PrivateExpense: 'PRIVATE_EXPENSE',
    Deposit: 'DEPOSIT',
    KittyExpense: 'KITTY_EXPENSE',
    KittyAdjustment: 'KITTY_ADJUSTMENT',
    PriceChange: 'PRICE_CHANGE',
    Rating: 'RATING'
} as const;
export type ActivityEntryType = typeof ActivityEntryType[keyof typeof ActivityEntryType];

