/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminExpenseDto { 
    weightGrams: number;
    amountCents: number;
    privateAmountCents: number;
    kittyAmountCents: number;
    note?: string | null;
}

