/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminExpenseDto { 
    expenseType: AdminExpenseDto.ExpenseTypeEnum;
    beanName?: string | null;
    weightGrams?: number | null;
    amountCents: number;
    privateAmountCents: number;
    kittyAmountCents: number;
    note?: string | null;
}
export namespace AdminExpenseDto {
    export const ExpenseTypeEnum = {
        Beans: 'BEANS',
        Other: 'OTHER'
    } as const;
    export type ExpenseTypeEnum = typeof ExpenseTypeEnum[keyof typeof ExpenseTypeEnum];
}


