/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoffeeBeanRatingsDto { 
    beanId: string;
    name: string;
    averageValue?: number | null;
    voteCount: number;
    latestRatingAt?: string | null;
    latestPurchaseAt?: string | null;
}

