/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsumptionChangeDto } from './consumptionChangeDto';


export interface ConsumptionDto { 
    total: number;
    changes: Array<ConsumptionChangeDto>;
}

