/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The new, non-negative total and an optional note.
 */
export interface ConsumptionOverrideDto { 
    total: number;
    note?: string | null;
}

