/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsumptionChangeDto { 
    count: number;
    delta: number;
    createdAt: string;
    createdBy: string;
    note?: string | null;
}

