/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The single-step delta to apply (+1 or -1).
 */
export interface ConsumptionDeltaDto { 
    delta: number;
}

