/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorResponse { 
    errorCode?: string;
    message?: string;
    statusCode?: number;
    statusMessage?: string;
    timestamp?: string;
    path?: string;
}

