/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ExpenseType = {
    Beans: 'BEANS',
    Other: 'OTHER'
} as const;
export type ExpenseType = typeof ExpenseType[keyof typeof ExpenseType];

