/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseType } from './expenseType';


export interface ExpenseDto { 
    id: string;
    buyerUserId: string;
    buyerLoginName: string;
    expenseType: ExpenseType;
    beanId?: string | null;
    beanName?: string | null;
    weightGrams?: number | null;
    amountCents: number;
    privateAmountCents: number;
    kittyAmountCents: number;
    note?: string | null;
    createdAt?: string | null;
}
export namespace ExpenseDto {
}


