/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityEntryType } from './activityEntryType';


export interface GlobalActivityEntryDto { 
    type: ActivityEntryType;
    id: string;
    createdAt: string;
    actorLogin: string;
    subjectUserId?: string | null;
    subjectLogin?: string | null;
    subjectName?: string | null;
    note?: string | null;
    userEffectCents?: number | null;
    userBalanceCents?: number | null;
    kittyEffectCents?: number | null;
    kittyBalanceCents?: number | null;
    count?: number | null;
    delta?: number | null;
    weightGrams?: number | null;
    privateAmountCents?: number | null;
    kittyAmountCents?: number | null;
    priceAmountCents?: number | null;
    beanName?: string | null;
    ratingValue?: number | null;
}
export namespace GlobalActivityEntryDto {
}


