/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LedgerEntryDto } from './ledgerEntryDto';


export interface KittyDto { 
    balanceCents: number;
    entries: Array<LedgerEntryDto>;
}

