/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LedgerEntryDto { 
    type: LedgerEntryDto.TypeEnum;
    id: string;
    createdAt: string;
    createdBy: string;
    note?: string | null;
    amountCents: number;
    runningBalanceCents: number;
    count?: number | null;
    delta?: number | null;
    weightGrams?: number | null;
    privateAmountCents?: number | null;
    kittyAmountCents?: number | null;
}
export namespace LedgerEntryDto {
    export const TypeEnum = {
        Consumption: 'CONSUMPTION',
        ConsumptionCancel: 'CONSUMPTION_CANCEL',
        PrivateExpense: 'PRIVATE_EXPENSE',
        Settlement: 'SETTLEMENT',
        KittyExpense: 'KITTY_EXPENSE',
        KittyAdjustment: 'KITTY_ADJUSTMENT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


