/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LedgerEntryDto } from './ledgerEntryDto';


export interface MemberSummaryDto { 
    count: number;
    priceCents: number;
    balanceCents: number;
    kittyBalanceCents: number;
    cancellable: boolean;
    ledger: Array<LedgerEntryDto>;
}

