/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentDto { 
    id: string;
    userId?: string | null;
    userLoginName?: string | null;
    amountCents: number;
    note?: string | null;
    createdAt?: string | null;
}

