/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SummaryPanel } from './summaryPanel';


/**
 * The profile fields to update.
 */
export interface ProfileUpdateDto { 
    firstName: string;
    lastName: string;
    emailAddress: string;
    summaryPanel: SummaryPanel;
}
export namespace ProfileUpdateDto {
}


