/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The profile fields to update.
 */
export interface ProfileUpdateDto { 
    firstName: string;
    lastName: string;
    emailAddress: string;
    summaryPanel: ProfileUpdateDto.SummaryPanelEnum;
}
export namespace ProfileUpdateDto {
    export const SummaryPanelEnum = {
        Balance: 'BALANCE',
        Cups: 'CUPS'
    } as const;
    export type SummaryPanelEnum = typeof SummaryPanelEnum[keyof typeof SummaryPanelEnum];
}


