/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Role = {
    User: 'USER',
    Admin: 'ADMIN'
} as const;
export type Role = typeof Role[keyof typeof Role];

