/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { SummaryPanel } from './summaryPanel';


/**
 * Data of the user to create, including their role.
 */
export interface UserDto { 
    id?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    loginName: string;
    emailAddress: string;
    firstName: string;
    lastName: string;
    password?: string | null;
    role?: Role | null;
    active?: boolean | null;
    summaryPanel?: SummaryPanel | null;
    readonly totpEnabled?: boolean | null;
    capabilityUrl?: string | null;
}
export namespace UserDto {
}


