/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SummaryPanel } from './summaryPanel';
import { CoffeeRatingPromptDto } from './coffeeRatingPromptDto';
import { ActivityEntryDto } from './activityEntryDto';


export interface UserSummaryDto { 
    count: number;
    priceCents: number;
    balanceCents: number;
    kittyBalanceCents: number;
    cancellable: boolean;
    summaryPanel: SummaryPanel;
    firstCupAt?: string | null;
    cupsThisWeek: number;
    cupsToday: number;
    ratingPrompt: CoffeeRatingPromptDto;
    activity: Array<ActivityEntryDto>;
}
export namespace UserSummaryDto {
}


