/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserBalanceDto { 
    userId: string;
    loginName: string;
    firstName: string;
    lastName: string;
    count: number;
    balanceCents: number;
}

