/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data of the member to create, including their role.
 */
export interface UserDto { 
    id?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    loginName: string;
    emailAddress: string;
    firstName: string;
    lastName: string;
    password?: string | null;
    role?: UserDto.RoleEnum | null;
    active?: boolean | null;
    capabilityUrl?: string | null;
}
export namespace UserDto {
    export const RoleEnum = {
        User: 'USER',
        Admin: 'ADMIN'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


