/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityEntryDto } from './activityEntryDto';


export interface UserSummaryDto { 
    count: number;
    priceCents: number;
    balanceCents: number;
    kittyBalanceCents: number;
    cancellable: boolean;
    summaryPanel: UserSummaryDto.SummaryPanelEnum;
    firstCupAt?: string | null;
    cupsThisWeek: number;
    cupsToday: number;
    activity: Array<ActivityEntryDto>;
}
export namespace UserSummaryDto {
    export const SummaryPanelEnum = {
        Balance: 'BALANCE',
        Cups: 'CUPS'
    } as const;
    export type SummaryPanelEnum = typeof SummaryPanelEnum[keyof typeof SummaryPanelEnum];
}


