/**
 * CampusCoffeeConsumption API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityEntryDto } from './activityEntryDto';


export interface UserSummaryDto { 
    count: number;
    priceCents: number;
    balanceCents: number;
    kittyBalanceCents: number;
    cancellable: boolean;
    activity: Array<ActivityEntryDto>;
}

