// @ts-check
// ESLint flat config for the Angular SPA, generated by `ng add angular-eslint` and then tuned for this
// project. It mirrors the backend's detekt/ktlint gates: angular-eslint's recommended TypeScript and
// template rule sets plus typescript-eslint's recommended + stylistic sets, with two opinionated
// architectural rules turned off (see below) and Prettier's formatting rules disabled so Prettier alone
// owns formatting. Run via `npm run lint` (which also runs Stylelint).
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');
const prettier = require('eslint-config-prettier');

module.exports = defineConfig([
  {
    // Build output, dependencies, the generated OpenAPI DTOs (src/app/api, produced by
    // openapi-generator and re-exported through src/app/models.ts, not hand-written, so the app's
    // stylistic rules do not apply), and the Playwright e2e suite (linted by its own
    // tsconfig/Playwright, not part of the Angular app graph) are out of scope for the app lint.
    ignores: ['dist/**', 'node_modules/**', '.angular/**', 'out-tsc/**', 'e2e/**', 'src/app/api/**'],
  },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'cc',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'cc',
          style: 'kebab-case',
        },
      ],
      // The team keeps constructor dependency injection as the default; do NOT push the inject() function.
      // (angular-eslint enables this in its recommended set as of v22; we opt back out deliberately.)
      '@angular-eslint/prefer-inject': 'off',
      // The app uses Angular's default (zone-based) change detection across all components; we have not
      // adopted an OnPush-everywhere policy, so this recommended-set rule is turned off rather than forcing
      // an architecture migration. Revisit if the app moves to OnPush/signals.
      '@angular-eslint/prefer-on-push-component-change-detection': 'off',
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {
      // Keep strict equality, but allow the idiomatic `x == null` / `x != null` nullish check (which
      // intentionally matches both null and undefined); turning those into `===`/`!==` would change
      // semantics. Mirrors typescript-eslint's eqeqeq `{ null: 'ignore' }`.
      '@angular-eslint/template/eqeqeq': ['error', { allowNullOrUndefined: true }],
    },
  },
  // Keep this last: disables any ESLint rules that would conflict with Prettier's formatting.
  prettier,
]);
