package de.seuhd.campuscoffee.domain.model

import java.time.LocalDateTime
import java.util.UUID

/**
 * Immutable user domain model: an SE@UHD user. Fields are validated in the API layer via
 * the DTOs.
 *
 * Several fields are populated by the lower layers rather than supplied by the client, and are therefore
 * nullable on the way in:
 * - [password] is the raw, plaintext password and is only ever set on the way *in* (only an admin sets
 *   one); the domain hashes it via the `PasswordHasherService` port and never reads it back. [passwordHash] is
 *   the stored hash, populated when a user is *read* and never serialized to a client.
 * - [capabilityToken] is the user's secret capability token: the unguessable value embedded in their
 *   QR/coffee link. It is generated by the data layer on creation (or replaced on rotation), is unique,
 *   and reaches a client only as part of the assembled capability URL, never as a raw field.
 * - [role] is the user's single authorization level and [active] whether the account may still mutate its
 *   count (a deactivated user is kept for history but authenticates read-only). Both are nullable on the
 *   way *in* with the same "not given" meaning the password fields use: a partial update DTO omits them,
 *   and the service then keeps the stored value (or defaults `role` to [Role.USER] / `active` to `true` on
 *   create). A user read back from the store always carries both.
 * - [summaryPanel] is the user's own display preference for the second card on their landing: [SummaryPanel.BALANCE]
 *   (the money) or [SummaryPanel.CUPS] (coffee stats). It follows the same nullable accept-or-keep pattern
 *   (omitted keeps the stored value, defaults to [SummaryPanel.BALANCE] on create); a user read back from the
 *   store always carries it.
 */
data class User(
    override val id: UUID? = null,
    val createdAt: LocalDateTime? = null,
    val updatedAt: LocalDateTime? = null,
    val loginName: String,
    val emailAddress: String,
    val firstName: String,
    val lastName: String,
    val role: Role? = null,
    val active: Boolean? = null,
    val summaryPanel: SummaryPanel? = null,
    val capabilityToken: String? = null,
    val passwordHash: String? = null,
    val password: String? = null
) : DomainModel<UUID>
